_core:
  default_config_hash: VDJxTZtQR21qB4lvOq8zszJZLvLKrSPQpdn2E3T71Ww
langcode: en
uuid: 03165082-6319-44ee-af68-69e3dc53b160
name: 'Learning Drupal'
mail: thapaanupa@gmail.com
slogan: 'Slow and Steady Wins the Race'
page:
  403: ''
  404: ''
  front: /node
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
